In [3]:
import numpy as np

In [9]:
arr = np.array([11,22,33,44,55])
arr

array([11, 22, 33, 44, 55])

In [21]:
b = np.delete(arr,0,axis=0)
b

array([22, 33, 44, 55])

In [23]:
mArr = np.array([[1,2,3],[4,5,6],[7,8,9]])
mArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
b = np.delete(mArr,slice(0,5),0)
b

array([], shape=(0, 3), dtype=int32)